language: ruby
install:
  - bundle install --without development
before_script:
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
rvm:
  - "1.9.2"
  - "1.9.3"
  - rbx-19mode
  - jruby-19mode
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head